version: '3'

networks:
  seek_workspace:

services:
  postgres:
    # TypeORM fails with Postgres v.12
    image: postgres:11.5
    ports:
      - 5455:5432
    environment:
      POSTGRES_USER: sws
      POSTGRES_PASSWORD: sws!@#pg
      POSTGRES_DB: seek_workspace
    volumes:
      - /Users/guiseek/Docker/PostgrelSQL:/var/lib/postgresql/data
    networks:
      - seek_workspace

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "sws"
      PGADMIN_DEFAULT_PASSWORD: "sws!@#pg"
    ports:
      - "16543:80"
    depends_on:
      - postgres
    networks:
      - seek_workspace

  redis:
    image: redis:alpine
    ports:
      - 6399:6379
    command: redis-server
    networks:
      - seek_workspace
